{
  "openapi": "3.0.1",
  "info": {
    "title": "Property Booking Website",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/api/v1/properties/{propertyId}/amenities/{amenityId}": {
      "post": {
        "summary": "新增指定房源設施",
        "deprecated": false,
        "description": "",
        "tags": ["property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "2",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "amenityId",
            "in": "path",
            "description": "設施 ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": "ok"
                  }
                }
              }
            }
          }
        },
        "security": []
      },
      "delete": {
        "summary": "刪除指定房源設施",
        "deprecated": false,
        "description": "",
        "tags": ["property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "amenityId",
            "in": "path",
            "description": "設施 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": "ok"
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/properties/{propertyId}/amenities": {
      "get": {
        "summary": "取得指定房源設施",
        "deprecated": false,
        "description": "",
        "tags": ["property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "amenities": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "amenityId": {
                              "type": "integer",
                              "title": "設施 ID"
                            },
                            "amenityName": {
                              "type": "string",
                              "title": "設施名稱"
                            },
                            "amenityTypeId": {
                              "type": "integer",
                              "title": "設施類型 ID"
                            }
                          },
                          "required": [
                            "amenityId",
                            "amenityName",
                            "amenityTypeId"
                          ]
                        },
                        "title": "設施列表"
                      },
                      "amenityTypeName": {
                        "type": "string",
                        "title": "設施類型名稱"
                      },
                      "amenityTypeId": {
                        "type": "integer",
                        "title": "設施類型 ID"
                      }
                    },
                    "required": [
                      "amenities",
                      "amenityTypeName",
                      "amenityTypeId"
                    ]
                  }
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": [
                      {
                        "amenities": [
                          {
                            "amenityId": 1,
                            "amenityName": "吹風機",
                            "amenityTypeId": 1
                          },
                          {
                            "amenityId": 2,
                            "amenityName": "沐浴乳",
                            "amenityTypeId": 1
                          },
                          {
                            "amenityId": 3,
                            "amenityName": "洗髮露",
                            "amenityTypeId": 1
                          },
                          {
                            "amenityId": 4,
                            "amenityName": "浴缸",
                            "amenityTypeId": 1
                          },
                          {
                            "amenityId": 5,
                            "amenityName": "熱水",
                            "amenityTypeId": 1
                          }
                        ],
                        "amenityTypeName": "衛浴",
                        "amenityTypeId": 1
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 6,
                            "amenityName": "洗衣機",
                            "amenityTypeId": 2
                          },
                          {
                            "amenityId": 7,
                            "amenityName": "衣櫥",
                            "amenityTypeId": 2
                          },
                          {
                            "amenityId": 8,
                            "amenityName": "衣架",
                            "amenityTypeId": 2
                          },
                          {
                            "amenityId": 9,
                            "amenityName": "保險箱",
                            "amenityTypeId": 2
                          }
                        ],
                        "amenityTypeName": "臥室和洗衣",
                        "amenityTypeId": 2
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 10,
                            "amenityName": "主題房間",
                            "amenityTypeId": 3
                          },
                          {
                            "amenityId": 11,
                            "amenityName": "乒乓球桌",
                            "amenityTypeId": 3
                          },
                          {
                            "amenityId": 12,
                            "amenityName": "保齡球",
                            "amenityTypeId": 3
                          },
                          {
                            "amenityId": 13,
                            "amenityName": "滑板坡道",
                            "amenityTypeId": 3
                          },
                          {
                            "amenityId": 14,
                            "amenityName": "迷你高爾夫",
                            "amenityTypeId": 3
                          }
                        ],
                        "amenityTypeName": "娛樂",
                        "amenityTypeId": 3
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 15,
                            "amenityName": "兒童自行車",
                            "amenityTypeId": 4
                          },
                          {
                            "amenityId": 16,
                            "amenityName": "兒童遊戲室",
                            "amenityTypeId": 4
                          },
                          {
                            "amenityId": 17,
                            "amenityName": "嬰兒浴盆",
                            "amenityTypeId": 4
                          },
                          {
                            "amenityId": 18,
                            "amenityName": "戶外遊樂場",
                            "amenityTypeId": 4
                          },
                          {
                            "amenityId": 19,
                            "amenityName": "桌遊",
                            "amenityTypeId": 4
                          }
                        ],
                        "amenityTypeName": "親子",
                        "amenityTypeId": 4
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 20,
                            "amenityName": "Wi-Fi",
                            "amenityTypeId": 5
                          },
                          {
                            "amenityId": 21,
                            "amenityName": "專屬工作空間",
                            "amenityTypeId": 5
                          }
                        ],
                        "amenityTypeName": "網路和辦公",
                        "amenityTypeId": 5
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 22,
                            "amenityName": "冰箱",
                            "amenityTypeId": 6
                          },
                          {
                            "amenityId": 23,
                            "amenityName": "冷凍庫",
                            "amenityTypeId": 6
                          },
                          {
                            "amenityId": 24,
                            "amenityName": "咖啡",
                            "amenityTypeId": 6
                          },
                          {
                            "amenityId": 25,
                            "amenityName": "基本廚具",
                            "amenityTypeId": 6
                          },
                          {
                            "amenityId": 26,
                            "amenityName": "微波爐",
                            "amenityTypeId": 6
                          }
                        ],
                        "amenityTypeName": "廚房和餐飲",
                        "amenityTypeId": 6
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 27,
                            "amenityName": "湖畔",
                            "amenityTypeId": 7
                          },
                          {
                            "amenityId": 28,
                            "amenityName": "濱水",
                            "amenityTypeId": 7
                          },
                          {
                            "amenityId": 29,
                            "amenityName": "直達海灘",
                            "amenityTypeId": 7
                          },
                          {
                            "amenityId": 30,
                            "amenityName": "直達滑雪場",
                            "amenityTypeId": 7
                          },
                          {
                            "amenityId": 31,
                            "amenityName": "度假村入場證",
                            "amenityTypeId": 7
                          }
                        ],
                        "amenityTypeName": "位置特色",
                        "amenityTypeId": 7
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/properties/{propertyId}/discounts": {
      "post": {
        "summary": "新增指定房源折扣",
        "deprecated": false,
        "description": "",
        "tags": ["property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "leastNumOfBookingDays": {
                    "type": "string",
                    "title": "訂房天數下限"
                  },
                  "discountValue": {
                    "type": "string",
                    "title": "折扣數量"
                  }
                },
                "required": [
                  "leastNumOfBookingDays",
                  "discountValue"
                ]
              },
              "example": {
                "leastNumOfBookingDays": 7,
                "discountValue": 30
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": "ok"
                  }
                }
              }
            }
          }
        },
        "security": []
      },
      "get": {
        "summary": "取得指定房源折扣",
        "deprecated": false,
        "description": "",
        "tags": ["property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "propertyId",
            "in": "query",
            "description": "房源 ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "discountId": {
                        "type": "integer",
                        "title": "折扣 ID"
                      },
                      "leastNumOfBookingDays": {
                        "type": "integer",
                        "title": "預定天數下限"
                      },
                      "discountValue": {
                        "type": "integer",
                        "title": "折扣數量"
                      }
                    },
                    "required": [
                      "discountId",
                      "leastNumOfBookingDays",
                      "discountValue"
                    ]
                  }
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": [
                      {
                        "discountId": 1,
                        "leastNumOfBookingDays": 7,
                        "discountValue": 10
                      },
                      {
                        "discountId": 2,
                        "leastNumOfBookingDays": 14,
                        "discountValue": 15
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/properties/{propertyId}/discounts/{discountId}": {
      "delete": {
        "summary": "刪除指定房源折扣",
        "deprecated": false,
        "description": "",
        "tags": ["property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "discountId",
            "in": "path",
            "description": "折扣 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": "ok"
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/properties/{propertyId}/picture-upload-urls": {
      "get": {
        "summary": "取得指定房源的圖片上傳連結",
        "deprecated": false,
        "description": "This is a POST request, submitting data to an API via the request body. This request submits JSON data, and the data is reflected in the response.\n\nA successful POST request typically returns a `200 OK` or `201 Created` response code.",
        "tags": ["property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "fileExtension",
            "in": "query",
            "description": "圖片副檔名",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "pictureId": {
                      "type": "integer",
                      "title": "房源 ID"
                    },
                    "size3": {
                      "type": "string",
                      "title": "圖片尺寸代號 3 的圖片上傳連結"
                    },
                    "sizeOriginal": {
                      "type": "string",
                      "title": "原始圖片的連結"
                    },
                    "size1": {
                      "type": "string",
                      "title": "圖片尺寸代號 1 的圖片上傳連結"
                    },
                    "size2": {
                      "type": "string",
                      "title": "圖片尺寸代號 2 的圖片上傳連結"
                    }
                  },
                  "required": [
                    "pictureId",
                    "size3",
                    "sizeOriginal",
                    "size1",
                    "size2"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": {
                      "pictureId": 10,
                      "size3": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-3/c79a6dcc-89fa-4e12-97a8-79e8dd2240b8.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240430T135003Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=%2A%2A%2A%2A%2A%2A%2A%2A%2F20240430%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=c9b626a3b144dcb0003eb83159b9a06e6ecc16783b7658d49652369573184360",
                      "sizeOriginal": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-original/7e22c187-f474-40ee-b418-0ac525628eb4.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240430T135003Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=%2A%2A%2A%2A%2A%2A%2A%2A%2F20240430%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=c5eb55272d668d95bd76c5753c2ac2b78cf318e2cbef165fcef8e1eee12e7e94",
                      "size1": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-1/cf873796-571a-4973-924c-bded85771fc4.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240430T135003Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=%2A%2A%2A%2A%2A%2A%2A%2A%2F20240430%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=89c539970192933a231b79b39c9fa9e2e1111f881ef2b29cc56ed93d45117e15",
                      "size2": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-2/1a13132b-534b-4004-9dff-bf8acc90fa59.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240430T135003Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=%2A%2A%2A%2A%2A%2A%2A%2A%2F20240430%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=0e1bda654c0a214220f18911f29678a5d446c190c4e93c21e35db2ae3afb6a5d"
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/properties/{propertyId}/picture-download-urls": {
      "get": {
        "summary": "取得指定房源的圖片下載連結",
        "deprecated": false,
        "description": "",
        "tags": ["property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sizeNum",
            "in": "query",
            "description": "圖片尺寸代號",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "pictureOrder": {
                        "type": "integer",
                        "title": "圖片順序"
                      },
                      "downloadUrl": {
                        "type": "string",
                        "title": "下載連結"
                      },
                      "sizeNum": {
                        "type": "integer",
                        "title": "圖片尺寸代號"
                      }
                    },
                    "required": [
                      "pictureOrder",
                      "downloadUrl",
                      "sizeNum"
                    ]
                  }
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": [
                      {
                        "pictureOrder": 1,
                        "downloadUrl": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-1/d7640f50-66d4-4c3a-bb4f-f34837248f11.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240430T135212Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=%2A%2A%2A%2A%2A%2A%2A%2A%2F20240430%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=ade42c7f7dbd9af44966b1eac07ec7799ad5f303b9012a2eab4c40d34c1d816c",
                        "sizeNum": 1
                      },
                      {
                        "pictureOrder": 2,
                        "downloadUrl": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-1/d7640f50-66d4-4c3a-bb4f-f34837248g11.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240430T135212Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=%2A%2A%2A%2A%2A%2A%2A%2A%2F20240430%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=9dcf86e1b2a91917322464e2bc28f1ffdeaac45b35162216c0fb085e13771070",
                        "sizeNum": 1
                      },
                      {
                        "pictureOrder": 3,
                        "downloadUrl": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-1/d7640f50-66d4-4c3a-bb4f-f34837248h11.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240430T135212Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=%2A%2A%2A%2A%2A%2A%2A%2A%2F20240430%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=15b1fad682ac53fecd4f7813e80b0c3280ce0d0ad5a177bff48b3480b65d2745",
                        "sizeNum": 1
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/properties/{propertyId}/property-pictures": {
      "post": {
        "summary": "新增指定房源的圖片",
        "deprecated": false,
        "description": "",
        "tags": ["property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "pictureId": {
                    "type": "integer",
                    "title": "圖片 ID"
                  },
                  "pictureOrder": {
                    "type": "integer",
                    "title": "圖片順序"
                  }
                },
                "required": [
                  "pictureId",
                  "pictureOrder"
                ]
              },
              "example": {
                "pictureId": 10,
                "pictureOrder": 4
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": "ok"
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/properties": {
      "post": {
        "summary": "新增房源",
        "deprecated": false,
        "description": "",
        "tags": ["property"],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "propertyTitle": {
                    "type": "string",
                    "title": "房源名稱"
                  },
                  "propertyDiscription": {
                    "type": "string",
                    "title": "房源描述"
                  },
                  "maxNumOfGuests": {
                    "type": "integer",
                    "title": "房客人數上限"
                  },
                  "numOfBathrooms": {
                    "type": "integer",
                    "title": "衛浴數量"
                  },
                  "numOfBeds": {
                    "type": "integer",
                    "title": "床位數量"
                  },
                  "numOfBedrooms": {
                    "type": "integer",
                    "title": "寢室數量"
                  },
                  "priceOnWeekdays": {
                    "type": "integer",
                    "title": "平日價格"
                  },
                  "priceOnWeekends": {
                    "type": "integer",
                    "title": "週末價格"
                  },
                  "isPublished": {
                    "type": "boolean",
                    "title": "是否發布"
                  },
                  "propertyMainSubTypeId": {
                    "type": "integer",
                    "title": "房源主次類型  ID"
                  },
                  "propertyShareTypeId": {
                    "type": "integer",
                    "title": "房源共享類型  ID"
                  },
                  "addressId": {
                    "type": "integer",
                    "title": "地址 ID"
                  }
                },
                "required": [
                  "propertyTitle"
                ]
              },
              "example": {
                "propertyTitle": "森林小屋",
                "propertyDiscription": "在森林裡的小木屋",
                "maxNumOfGuests": 1,
                "numOfBathrooms": 1,
                "numOfBeds": 1,
                "numOfBedrooms": 1,
                "priceOnWeekdays": 1500,
                "priceOnWeekends": 3000,
                "isPublished": true,
                "propertyMainSubTypeId": 1,
                "propertyShareTypeId": 1,
                "addressId": 1
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": "ok"
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/properties/{propertyId}": {
      "patch": {
        "summary": "修改指定房源",
        "deprecated": false,
        "description": "",
        "tags": ["property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{jwt_token}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "propertyTitle": {
                    "type": "string",
                    "title": "房源名稱"
                  },
                  "propertyDiscription": {
                    "type": "string",
                    "title": "房源描述"
                  },
                  "maxNumOfGuests": {
                    "type": "integer",
                    "title": "房客人數上限"
                  },
                  "numOfBathrooms": {
                    "type": "integer",
                    "title": "衛浴數量"
                  },
                  "numOfBeds": {
                    "type": "integer",
                    "title": "床位數量"
                  },
                  "numOfBedrooms": {
                    "type": "integer",
                    "title": "寢室數量"
                  },
                  "priceOnWeekdays": {
                    "type": "integer",
                    "title": "平日價格"
                  },
                  "priceOnWeekends": {
                    "type": "integer",
                    "title": "週末價格"
                  },
                  "isPublished": {
                    "type": "boolean",
                    "title": "是否發不"
                  },
                  "propertyMainSubTypeId": {
                    "type": "integer",
                    "title": "房源主次類型  ID"
                  },
                  "propertyShareTypeId": {
                    "type": "integer",
                    "title": "房源共享類型  ID"
                  },
                  "addressId": {
                    "type": "integer",
                    "title": "地址 ID"
                  }
                },
                "required": [
                  "propertyTitle",
                  "propertyDiscription",
                  "maxNumOfGuests",
                  "numOfBathrooms",
                  "numOfBeds",
                  "numOfBedrooms",
                  "priceOnWeekdays",
                  "priceOnWeekends",
                  "isPublished",
                  "propertyMainSubTypeId",
                  "propertyShareTypeId",
                  "addressId"
                ]
              },
              "example": {
                "propertyTitle": "森林小屋",
                "propertyDiscription": "在森林裡的小木屋",
                "maxNumOfGuests": 1,
                "numOfBathrooms": 1,
                "numOfBeds": 1,
                "numOfBedrooms": 1,
                "priceOnWeekdays": 1500,
                "priceOnWeekends": 3000,
                "isPublished": true,
                "propertyMainSubTypeId": 1,
                "propertyShareTypeId": 1,
                "addressId": 1
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": "ok"
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  },
  "servers": []
}