{
  "openapi": "3.0.1",
  "info": {
    "title": "Property Booking Website",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/api/v1/public-properties": {
      "get": {
        "summary": "取得已發布的房源",
        "deprecated": false,
        "description": "",
        "tags": ["public-property"],
        "parameters": [
          {
            "name": "numOfAvailableDays",
            "in": "query",
            "description": "指定連續預定天數，以找出房源最近符合可預訂天數的日期。不可與 startAvailableDateString、endAvailableDateString 同時存在。",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "startAvailableDateString",
            "in": "query",
            "description": "開始預定日期字串(YYYY-MM-DD)，搭配 endAvailableDateString以找出指定日期間可預訂的房源。不可與 numOfAvailableDays 同時存在。",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "endAvailableDateString",
            "in": "query",
            "description": "結束預定日期字串(YYYY-MM-DD)，搭配 startAvailableDateString以找出指定日期間可預訂的房源。不可與 numOfAvailableDays 同時存在。",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "numOfGuests",
            "in": "query",
            "description": "入住人數",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "numOfBedrooms",
            "in": "query",
            "description": "臥室數量",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "numOfBeds",
            "in": "query",
            "description": "床位數量",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "numOfBathrooms",
            "in": "query",
            "description": "衛浴數量",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "maxPrice",
            "in": "query",
            "description": "最高價格",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "minPrice",
            "in": "query",
            "description": "最低價格",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "propertyGroupId",
            "in": "query",
            "description": "房源群組 ID",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "propertyShareTypeId",
            "in": "query",
            "description": "房源共享類型 ID",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "amenityIds",
            "in": "query",
            "description": "設施 ID 列表",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "districtId",
            "in": "query",
            "description": "地區 ID",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "propertyId": {
                        "type": "integer",
                        "title": "房源 ID"
                      },
                      "propertyTitle": {
                        "type": "string",
                        "title": "房源名稱"
                      },
                      "propertyDescription": {
                        "type": "string",
                        "title": "房源描述"
                      },
                      "maxNumOfGuests": {
                        "type": "integer",
                        "title": "房客人數上限"
                      },
                      "numOfBedrooms": {
                        "type": "integer",
                        "title": "寢室數量"
                      },
                      "numOfBeds": {
                        "type": "integer",
                        "title": "床位數量"
                      },
                      "numOfBathrooms": {
                        "type": "integer",
                        "title": "衛浴數量"
                      },
                      "priceOnWeekdays": {
                        "type": "integer",
                        "title": "平日價格"
                      },
                      "priceOnWeekends": {
                        "type": "integer",
                        "title": "週末價格"
                      },
                      "isPublished": {
                        "type": "boolean",
                        "title": "是否發布"
                      },
                      "averageRating": {
                        "type": "integer",
                        "title": "平均評價分數"
                      },
                      "reviewCount": {
                        "type": "integer",
                        "title": "評論數量"
                      },
                      "propertyMainSubTypeId": {
                        "type": "integer",
                        "title": "房源主次類型 ID"
                      },
                      "propertyShareTypeId": {
                        "type": "integer",
                        "title": "房源分享類型"
                      },
                      "addressId": {
                        "type": "integer",
                        "title": "地址 ID"
                      },
                      "hostId": {
                        "type": "integer",
                        "title": "出租人 ID"
                      },
                      "street": {
                        "type": "string",
                        "title": "街道名稱"
                      },
                      "districtId": {
                        "type": "integer",
                        "title": "地區 ID"
                      },
                      "parentDistrictId": {
                        "type": "integer",
                        "title": "父地區 ID"
                      },
                      "districtName": {
                        "type": "string",
                        "title": "地區名稱"
                      },
                      "parentDistrictName": {
                        "type": "string",
                        "title": "父地區名稱"
                      },
                      "startAvailableDate": {
                        "type": "string",
                        "title": "開始可預定日期",
                        "description": "若 request body 有帶 NumOfAvailableDays 或 startAvailableDateString 及 endAvailableDateString，則不為空值"
                      },
                      "endAvailableDate": {
                        "type": "string",
                        "title": "結束可預定日期",
                        "description": "若 request body 有帶 NumOfAvailableDays 或 startAvailableDateString 及 endAvailableDateString，則不為空值"
                      }
                    },
                    "required": [
                      "propertyId",
                      "propertyTitle",
                      "propertyDescription",
                      "maxNumOfGuests",
                      "numOfBedrooms",
                      "numOfBeds",
                      "numOfBathrooms",
                      "priceOnWeekdays",
                      "priceOnWeekends",
                      "isPublished",
                      "averageRating",
                      "reviewCount",
                      "propertyMainSubTypeId",
                      "propertyShareTypeId",
                      "addressId",
                      "hostId",
                      "street",
                      "districtId",
                      "parentDistrictId",
                      "districtName",
                      "parentDistrictName",
                      "startAvailableDate",
                      "endAvailableDate"
                    ]
                  }
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": [
                      {
                        "propertyId": 1,
                        "propertyTitle": "test property 1",
                        "propertyDescription": null,
                        "maxNumOfGuests": 2,
                        "numOfBedrooms": 1,
                        "numOfBeds": 2,
                        "numOfBathrooms": 1,
                        "priceOnWeekdays": 700,
                        "priceOnWeekends": 1000,
                        "isPublished": true,
                        "averageRating": 5,
                        "reviewCount": 1,
                        "propertyMainSubTypeId": null,
                        "propertyShareTypeId": null,
                        "addressId": 1,
                        "hostId": 1,
                        "street": "test street 1",
                        "districtId": 181,
                        "parentDistrictId": 165,
                        "districtName": "宜蘭市",
                        "parentDistrictName": "宜蘭縣",
                        "startAvailableDate": null,
                        "endAvailableDate": null
                      },
                      {
                        "propertyId": 2,
                        "propertyTitle": "test property 2",
                        "propertyDescription": null,
                        "maxNumOfGuests": 2,
                        "numOfBedrooms": 1,
                        "numOfBeds": 1,
                        "numOfBathrooms": 1,
                        "priceOnWeekdays": 800,
                        "priceOnWeekends": 1200,
                        "isPublished": true,
                        "averageRating": 5,
                        "reviewCount": 1,
                        "propertyMainSubTypeId": null,
                        "propertyShareTypeId": null,
                        "addressId": 1,
                        "hostId": 1,
                        "street": "test street 1",
                        "districtId": 181,
                        "parentDistrictId": 165,
                        "districtName": "宜蘭市",
                        "parentDistrictName": "宜蘭縣",
                        "startAvailableDate": null,
                        "endAvailableDate": null
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/public-properties/{propertyId}": {
      "get": {
        "summary": "取得指定的已發布房源",
        "deprecated": false,
        "description": "",
        "tags": ["public-property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "propertyId": {
                      "type": "integer",
                      "title": "房源 ID"
                    },
                    "propertyTitle": {
                      "type": "string",
                      "title": "房源名稱"
                    },
                    "propertyDescription": {
                      "type": "string",
                      "title": "房源描述"
                    },
                    "maxNumOfGuests": {
                      "type": "integer",
                      "title": "房客人數上限"
                    },
                    "numOfBedrooms": {
                      "type": "integer",
                      "title": "寢室數量"
                    },
                    "numOfBeds": {
                      "type": "integer",
                      "title": "床位數量"
                    },
                    "numOfBathrooms": {
                      "type": "integer",
                      "title": "衛浴數量"
                    },
                    "priceOnWeekdays": {
                      "type": "integer",
                      "title": "平日價格"
                    },
                    "priceOnWeekends": {
                      "type": "integer",
                      "title": "週末價格"
                    },
                    "isPublished": {
                      "type": "boolean",
                      "title": "是否發布"
                    },
                    "averageRating": {
                      "type": "integer",
                      "title": "平均評價分數"
                    },
                    "reviewCount": {
                      "type": "integer",
                      "title": "評論數量"
                    },
                    "propertyMainSubTypeId": {
                      "type": "integer",
                      "title": "房源主次類型  ID"
                    },
                    "propertyShareTypeId": {
                      "type": "integer",
                      "title": "房源共享類型 ID"
                    },
                    "addressId": {
                      "type": "integer",
                      "title": "地址 ID"
                    },
                    "hostId": {
                      "type": "integer",
                      "title": "出租人 ID"
                    }
                  },
                  "required": [
                    "propertyId",
                    "propertyTitle",
                    "propertyDescription",
                    "maxNumOfGuests",
                    "numOfBedrooms",
                    "numOfBeds",
                    "numOfBathrooms",
                    "priceOnWeekdays",
                    "priceOnWeekends",
                    "isPublished",
                    "averageRating",
                    "reviewCount",
                    "propertyMainSubTypeId",
                    "propertyShareTypeId",
                    "addressId",
                    "hostId"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": {
                      "propertyId": 1,
                      "propertyTitle": "森林小屋1",
                      "propertyDescription": null,
                      "maxNumOfGuests": 2,
                      "numOfBedrooms": 1,
                      "numOfBeds": 2,
                      "numOfBathrooms": 1,
                      "priceOnWeekdays": 1500,
                      "priceOnWeekends": 3000,
                      "isPublished": true,
                      "averageRating": 5,
                      "reviewCount": 1,
                      "propertyMainSubTypeId": 1,
                      "propertyShareTypeId": 1,
                      "addressId": 1,
                      "hostId": 1
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/public-properties/{propertyId}/amenities": {
      "get": {
        "summary": "取得指定已發布房源的設施",
        "deprecated": false,
        "description": "",
        "tags": ["public-property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "amenities": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "amenityId": {
                              "type": "integer",
                              "title": "設施 ID"
                            },
                            "amenityName": {
                              "type": "string",
                              "title": "設施名稱"
                            },
                            "amenityTypeId": {
                              "type": "integer",
                              "title": "設施類型 ID"
                            }
                          },
                          "required": [
                            "amenityId",
                            "amenityName",
                            "amenityTypeId"
                          ]
                        },
                        "title": "設施列表"
                      },
                      "amenityTypeName": {
                        "type": "string",
                        "title": "設施類型名稱"
                      },
                      "amenityTypeId": {
                        "type": "integer",
                        "title": "設施類型 ID"
                      }
                    },
                    "required": [
                      "amenities",
                      "amenityTypeName",
                      "amenityTypeId"
                    ]
                  }
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": [
                      {
                        "amenities": [
                          {
                            "amenityId": 1,
                            "amenityName": "吹風機",
                            "amenityTypeId": 1
                          },
                          {
                            "amenityId": 2,
                            "amenityName": "沐浴乳",
                            "amenityTypeId": 1
                          },
                          {
                            "amenityId": 3,
                            "amenityName": "洗髮露",
                            "amenityTypeId": 1
                          },
                          {
                            "amenityId": 4,
                            "amenityName": "浴缸",
                            "amenityTypeId": 1
                          },
                          {
                            "amenityId": 5,
                            "amenityName": "熱水",
                            "amenityTypeId": 1
                          }
                        ],
                        "amenityTypeName": "衛浴",
                        "amenityTypeId": 1
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 6,
                            "amenityName": "洗衣機",
                            "amenityTypeId": 2
                          },
                          {
                            "amenityId": 7,
                            "amenityName": "衣櫥",
                            "amenityTypeId": 2
                          },
                          {
                            "amenityId": 8,
                            "amenityName": "衣架",
                            "amenityTypeId": 2
                          },
                          {
                            "amenityId": 9,
                            "amenityName": "保險箱",
                            "amenityTypeId": 2
                          }
                        ],
                        "amenityTypeName": "臥室和洗衣",
                        "amenityTypeId": 2
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 10,
                            "amenityName": "主題房間",
                            "amenityTypeId": 3
                          },
                          {
                            "amenityId": 11,
                            "amenityName": "乒乓球桌",
                            "amenityTypeId": 3
                          },
                          {
                            "amenityId": 12,
                            "amenityName": "保齡球",
                            "amenityTypeId": 3
                          },
                          {
                            "amenityId": 13,
                            "amenityName": "滑板坡道",
                            "amenityTypeId": 3
                          },
                          {
                            "amenityId": 14,
                            "amenityName": "迷你高爾夫",
                            "amenityTypeId": 3
                          }
                        ],
                        "amenityTypeName": "娛樂",
                        "amenityTypeId": 3
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 15,
                            "amenityName": "兒童自行車",
                            "amenityTypeId": 4
                          },
                          {
                            "amenityId": 16,
                            "amenityName": "兒童遊戲室",
                            "amenityTypeId": 4
                          },
                          {
                            "amenityId": 17,
                            "amenityName": "嬰兒浴盆",
                            "amenityTypeId": 4
                          },
                          {
                            "amenityId": 18,
                            "amenityName": "戶外遊樂場",
                            "amenityTypeId": 4
                          },
                          {
                            "amenityId": 19,
                            "amenityName": "桌遊",
                            "amenityTypeId": 4
                          }
                        ],
                        "amenityTypeName": "親子",
                        "amenityTypeId": 4
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 20,
                            "amenityName": "Wi-Fi",
                            "amenityTypeId": 5
                          },
                          {
                            "amenityId": 21,
                            "amenityName": "專屬工作空間",
                            "amenityTypeId": 5
                          }
                        ],
                        "amenityTypeName": "網路和辦公",
                        "amenityTypeId": 5
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 22,
                            "amenityName": "冰箱",
                            "amenityTypeId": 6
                          },
                          {
                            "amenityId": 23,
                            "amenityName": "冷凍庫",
                            "amenityTypeId": 6
                          },
                          {
                            "amenityId": 24,
                            "amenityName": "咖啡",
                            "amenityTypeId": 6
                          },
                          {
                            "amenityId": 25,
                            "amenityName": "基本廚具",
                            "amenityTypeId": 6
                          },
                          {
                            "amenityId": 26,
                            "amenityName": "微波爐",
                            "amenityTypeId": 6
                          }
                        ],
                        "amenityTypeName": "廚房和餐飲",
                        "amenityTypeId": 6
                      },
                      {
                        "amenities": [
                          {
                            "amenityId": 27,
                            "amenityName": "湖畔",
                            "amenityTypeId": 7
                          },
                          {
                            "amenityId": 28,
                            "amenityName": "濱水",
                            "amenityTypeId": 7
                          },
                          {
                            "amenityId": 29,
                            "amenityName": "直達海灘",
                            "amenityTypeId": 7
                          },
                          {
                            "amenityId": 30,
                            "amenityName": "直達滑雪場",
                            "amenityTypeId": 7
                          },
                          {
                            "amenityId": 31,
                            "amenityName": "度假村入場證",
                            "amenityTypeId": 7
                          }
                        ],
                        "amenityTypeName": "位置特色",
                        "amenityTypeId": 7
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/public-properties/{propertyId}/download-picture-urls": {
      "get": {
        "summary": "取得指定已發布房源的圖片下載連結",
        "deprecated": false,
        "description": "",
        "tags": ["public-property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sizeNum",
            "in": "query",
            "description": "尺寸代碼",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "pictureOrder": {
                        "type": "integer",
                        "title": "圖片順序"
                      },
                      "downloadUrl": {
                        "type": "string",
                        "title": "下載連結"
                      },
                      "sizeNum": {
                        "type": "integer",
                        "title": "圖片尺寸代號"
                      }
                    },
                    "required": [
                      "pictureOrder",
                      "downloadUrl",
                      "sizeNum"
                    ]
                  }
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": [
                      {
                        "pictureOrder": 1,
                        "downloadUrl": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-1/d7640f50-66d4-4c3a-bb4f-f34837248f11.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240424T073652Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=AKIAYUGJSPN7IY6RUGER%2F20240424%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=7314f8a33a420e88b3777174f51a9bce3f7bfe72821c192b12aa8d1c528a2cc9",
                        "sizeNum": 1
                      },
                      {
                        "pictureOrder": 2,
                        "downloadUrl": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-1/d7640f50-66d4-4c3a-bb4f-f34837248g11.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240424T073652Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=AKIAYUGJSPN7IY6RUGER%2F20240424%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=6537ae8c053c439ffb575a738ee84ee820ca14be3ce0631404b7c309dda8bd8c",
                        "sizeNum": 1
                      },
                      {
                        "pictureOrder": 3,
                        "downloadUrl": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-1/d7640f50-66d4-4c3a-bb4f-f34837248h11.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240424T073652Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=AKIAYUGJSPN7IY6RUGER%2F20240424%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=84e44d45a4a15d9329ca884927f370479d1032c12c4618f9e31a890c29f91412",
                        "sizeNum": 1
                      },
                      {
                        "pictureOrder": 4,
                        "downloadUrl": "https://property-booking-website-customer.s3-ap-northeast-1.amazonaws.com/properties/1/size-1/b068eaaa-7f1e-4826-86ff-6cb8350164ac.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240424T073652Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=AKIAYUGJSPN7IY6RUGER%2F20240424%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Signature=b118664f497f4be97a84541494bc97a7a50d86e454862108d1720953d4424d2b",
                        "sizeNum": 1
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/public-properties/{propertyId}/booking-calendars": {
      "get": {
        "summary": "取得指定已發布房源的預定日期",
        "deprecated": false,
        "description": "取得指定已公開發布房源的所有可預定及已預定日期",
        "tags": ["public-property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "bookingCalendarId": {
                        "type": "integer",
                        "title": "預定日曆 ID"
                      },
                      "bookingDate": {
                        "type": "string",
                        "title": "預定日期"
                      },
                      "propertyId": {
                        "type": "integer",
                        "title": "房源 ID"
                      }
                    },
                    "required": [
                      "bookingCalendarId",
                      "bookingDate",
                      "propertyId"
                    ]
                  }
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": [
                      {
                        "bookingCalendarId": 1,
                        "bookingDate": "2024-05-12",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 2,
                        "bookingDate": "2024-05-13",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 3,
                        "bookingDate": "2024-05-14",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 4,
                        "bookingDate": "2024-05-15",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 5,
                        "bookingDate": "2024-05-16",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 6,
                        "bookingDate": "2024-05-17",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 7,
                        "bookingDate": "2024-05-18",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 15,
                        "bookingDate": "2024-05-26",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 16,
                        "bookingDate": "2024-05-27",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 17,
                        "bookingDate": "2024-05-28",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 18,
                        "bookingDate": "2024-05-29",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 19,
                        "bookingDate": "2024-05-30",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 20,
                        "bookingDate": "2024-05-31",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 21,
                        "bookingDate": "2024-06-01",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 27,
                        "bookingDate": "2024-06-07",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 28,
                        "bookingDate": "2024-06-08",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 29,
                        "bookingDate": "2024-06-09",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 30,
                        "bookingDate": "2024-06-10",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 91,
                        "bookingDate": "2024-05-19",
                        "propertyId": 1
                      },
                      {
                        "bookingCalendarId": 92,
                        "bookingDate": "2024-05-20",
                        "propertyId": 1
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/public-properties/{propertyId}/property-reviews": {
      "get": {
        "summary": "取得指定已發布房源的評論",
        "deprecated": false,
        "description": "",
        "tags": ["public-property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "propertyReviewId": {
                        "type": "integer",
                        "title": "房源評論 ID"
                      },
                      "propertyReviewCleanliness": {
                        "type": "integer",
                        "title": "整潔度分數"
                      },
                      "propertyReviewAccuracy": {
                        "type": "integer",
                        "title": "準時度分數"
                      },
                      "propertyReviewCheckin": {
                        "type": "integer",
                        "title": "入住容易度分數"
                      },
                      "propertyReviewCommunication": {
                        "type": "integer",
                        "title": "溝通分數"
                      },
                      "propertyReviewLocation": {
                        "type": "integer",
                        "title": "地點分數"
                      },
                      "propertyReviewValue": {
                        "type": "integer",
                        "title": "性價比分數"
                      },
                      "propertyReviewComment": {
                        "type": "string",
                        "title": "評論內容"
                      },
                      "propertyReviewCreatedAt": {
                        "type": "string",
                        "title": "名論時間"
                      },
                      "propertyId": {
                        "type": "integer",
                        "title": "房源 ID"
                      },
                      "customerId": {
                        "type": "integer",
                        "title": "房客 ID"
                      },
                      "propertyAverageRating": {
                        "type": "integer",
                        "title": "平均分數"
                      }
                    }
                  }
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": [
                      {
                        "propertyReviewId": 1,
                        "propertyReviewCleanliness": 5,
                        "propertyReviewAccuracy": 5,
                        "propertyReviewCheckin": 5,
                        "propertyReviewCommunication": 5,
                        "propertyReviewLocation": 5,
                        "propertyReviewValue": 5,
                        "propertyReviewComment": "test comment",
                        "propertyReviewCreatedAt": "2024-04-09T00:00:00",
                        "propertyId": 1,
                        "customerId": 2,
                        "propertyAverageRating": 5
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/public-properties/{propertyId}/discounts": {
      "get": {
        "summary": "取得指定已發布房源的折扣",
        "deprecated": false,
        "description": "",
        "tags": ["public-property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "discountId": {
                        "type": "integer",
                        "title": "折扣 ID"
                      },
                      "leastNumOfBookingDays": {
                        "type": "integer",
                        "title": "訂房天數下限"
                      },
                      "discountValue": {
                        "type": "integer",
                        "title": "折扣數量"
                      }
                    }
                  }
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": [
                      {
                        "discountId": 1,
                        "leastNumOfBookingDays": 7,
                        "discountValue": 10
                      },
                      {
                        "discountId": 2,
                        "leastNumOfBookingDays": 14,
                        "discountValue": 15
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/public-properties/{propertyId}/bedrooms": {
      "get": {
        "summary": "取得指定已發布房源的房間",
        "deprecated": false,
        "description": "",
        "tags": ["public-property"],
        "parameters": [
          {
            "name": "propertyId",
            "in": "path",
            "description": "房源 ID",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "bedroomId": {
                        "type": "integer",
                        "title": "寢室 ID"
                      },
                      "numOfSingleBeds": {
                        "type": "integer",
                        "title": "單人床數量"
                      },
                      "numOfDoubleBeds": {
                        "type": "integer",
                        "title": "雙人床數量"
                      },
                      "propertyId": {
                        "type": "integer",
                        "title": "房源 ID"
                      }
                    }
                  }
                },
                "examples": {
                  "1": {
                    "summary": "200",
                    "value": [
                      {
                        "bedroomId": 1,
                        "numOfSingleBeds": 1,
                        "numOfDoubleBeds": 1,
                        "propertyId": 1
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  },
  "servers": []
}